pimcore_data_hub:
    configurations:
        TeamsImport:
            general:
                active: true
                type: dataImporterDataObject
                name: TeamsImport
                description: ''
                group: ''
                path: null
                modificationDate: 1725873238
                createDate: 1725788528
            loaderConfig:
                type: push
                settings:
                    apiKey: 7003910d30445c3d27e0e7419c485d4d
            interpreterConfig:
                type: xlsx
                settings:
                    skipFirstRow: true
                    sheetName: Teams
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: '1'
                loadingStrategy:
                    type: notLoad
                createLocationStrategy:
                    type: staticPath
                    settings:
                        path: /Teams/
                locationUpdateStrategy:
                    type: noChange
                publishingStrategy:
                    type: alwaysPublish
            processingConfig:
                executionType: parallel
                doArchiveImportFile: true
                idDataIndex: '0'
                cleanup:
                    strategy: delete
            mappingConfig:
                -
                    label: Name
                    dataSourceIndex:
                        - '1'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: Name
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: Trainer
                    dataSourceIndex:
                        - '3'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: Trainer
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: Logo
                    dataSourceIndex:
                        - '2'
                    settings:
                        parentFolder: /
                        useExisting: 'on'
                        overwriteExisting: 'on'
                        pregMatch: ''
                    transformationResultType: asset
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: Logo
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                parentFolder: /
                                useExisting: 'on'
                                overwriteExisting: 'on'
                                pregMatch: ''
                            type: importAsset
                -
                    label: Coordinates
                    dataSourceIndex:
                        - '5'
                        - '6'
                    transformationResultType: geoPoint
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: Coordinates
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: asGeopoint
                -
                    label: FoundingYear
                    dataSourceIndex:
                        - '7'
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: FoundingYear
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
                -
                    label: Key
                    dataSourceIndex:
                        - '0'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: key
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
            executionConfig:
                scheduleType: recurring
                scheduledAt: ''
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
