pimcore_static_routes:
    definitions:
        1ca08943-fec5-43cd-969d-40648671624a:
            name: Team
            pattern: '/\/team\/(.*)/'
            reverse: /team/%shortname
            controller: 'App\Controller\TeamsController::teamAction'
            variables: shortname
            defaults: ''
            siteId: {  }
            methods: {  }
            priority: 0
            creationDate: 1726063599
            modificationDate: 1726064244
